export {default as Footer} from "./ui/Footer"
export {default as Navbar} from "./ui/Navbar"
export {default as Hero} from "./home/Hero"
export {default as Testimonial} from "./home/Testimonial"
export {default as FAQ} from "./home/FAQ"